import { Product, Category, Coupon, Review, Order, InventoryTransaction, User, NotificationItem, HomepageBanner, StoreSettings } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'card-games',
    nameAr: 'ألعاب الكروت',
    nameEn: 'Card Games',
    icon: 'PlayingCard',
    image: '/cards/Speeeeeedy_Minimalist_Full_Card_4K_9x5.5cm.png',
    descriptionAr: 'مجموعة من أسرع وأمتع ألعاب التحدي بالكروت والسرعة للجمعات والعائلات.',
    descriptionEn: 'Fast-paced, thrill-packed card games for family and friend gatherings.',
    productCount: 8,
  },
  {
    id: 'cat-2',
    slug: 'board-games',
    nameAr: 'ألعاب الطاولة',
    nameEn: 'Board Games',
    icon: 'Grid',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80',
    descriptionAr: 'ألعاب الترابيزة الاستراتيجية الفاخرة المصنوعة بجودة عالية.',
    descriptionEn: 'Luxury strategy board games designed for immersive gameplay.',
    productCount: 6,
  },
  {
    id: 'cat-3',
    slug: 'party-games',
    nameAr: 'ألعاب الحفلات والتجمعات',
    nameEn: 'Party Games',
    icon: 'Sparkles',
    image: '/cards/Okef_3andak_9x5.5cm_Equal_Color_Bleed_4K.png',
    descriptionAr: 'ضحك وتحديات لا تنتهي مع أصدقائك في السهرات والمناسبات.',
    descriptionEn: 'Non-stop laughter and social challenges for group nights out.',
    productCount: 5,
  },
  {
    id: 'cat-4',
    slug: 'chess-classic',
    nameAr: 'الشطرنج والألعاب الكلاسيكية',
    nameEn: 'Chess & Classic Games',
    icon: 'Crown',
    image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=600&q=80',
    descriptionAr: 'طاولات شطرنج خشبية فاخرة وأطقم دمنة وطاولة زهر كلاسيكية.',
    descriptionEn: 'Handcrafted luxury wooden chess sets, dominoes, and classic backgammon.',
    productCount: 4,
  },
  {
    id: 'cat-5',
    slug: 'strategy-games',
    nameAr: 'ألعاب الذكاء والاستراتيجية',
    nameEn: 'Strategy Games',
    icon: 'Brain',
    image: 'https://images.unsplash.com/photo-1632501641765-e568d28b0015?auto=format&fit=crop&w=600&q=80',
    descriptionAr: 'خطط، تنافس، وسيطر على الرقعة في أعمق ألعاب التفكير التكتيكي.',
    descriptionEn: 'Plan, outsmart opponents, and dominate in tactical mastermind games.',
    productCount: 5,
  },
  {
    id: 'cat-6',
    slug: 'accessories',
    nameAr: 'إكسسوارات الألعاب',
    nameEn: 'Accessories & Sleeves',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=600&q=80',
    descriptionAr: 'جرابات حماية الكروت، نرد كريستالي، وحقائب قماشية فاخرة.',
    descriptionEn: 'Protective card sleeves, custom metal dice, and luxury game pouches.',
    productCount: 4,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-speeeeeedy',
    sku: '3Z-SPD-01',
    nameAr: 'لعبة سبيدي (Speeeeeedy!) الاصدار الذهبي',
    nameEn: 'Speeeeeedy! Card Game Gold Edition',
    descriptionAr: 'لعبة الكروت الأكثر حماساً وسرعة من عالم زاجك! تتطلب التركيز العالي، البديهة السريعة، وردود الأفعال الخاطفة. تجمع بين الخدع البصرية وتكتيك الكروت لتسحق منافسيك قبل أن ينتهي الوقت.',
    descriptionEn: 'The flagship rapid-fire card game from 3alamzagak! Requires lightning-fast reflexes, intense focus, and clever card combos. Outplay your rivals before the timer runs out!',
    shortDescriptionAr: 'لعبة السرعة والتركيز الأولى من عالم زاجك (2-4 لاعبين)',
    shortDescriptionEn: 'The ultimate speed & reflexes card game by 3alamzagak (2-4 Players)',
    price: 349,
    salePrice: 289,
    costPrice: 120,
    profitMargin: 58.4,
    categoryId: 'cat-1',
    categoryNameAr: 'ألعاب الكروت',
    categoryNameEn: 'Card Games',
    brand: '3alamzagak',
    images: [
      '/cards/Speeeeeedy_Minimalist_Full_Card_4K_9x5.5cm.png',
      '/cards/Speeeeeedy_Info_Card_2-4Players_4K_ExtraBleed_Full (1).png',
      '/cards/Speeeeeedy_Instructions_Bleed_4K_9x5.5cm.png',
    ],
    stock: 45,
    lowStockThreshold: 10,
    ageRecommendation: '7+',
    numberOfPlayers: '2-4 Players',
    minPlayers: 2,
    maxPlayers: 4,
    playingTimeMinutes: '15-20 mins',
    difficultyLevel: 'Medium',
    difficultyAr: 'متوسط',
    language: 'Bilingual',
    tags: ['Speeeeeedy', 'Speed', 'Best Seller', '3alamzagak Original', 'Cards'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 38,
    howToPlayAr: 'وزّع الكروت بالتساوي على اللاعبين. اسحب كرت بسرعة وضع النمط المطابق على الطاولة ونادِ "سبيدي!" أول لاعب يتخلص من كروته يفوز بالجولة.',
    howToPlayEn: 'Deal cards equally. Match pattern cards on the center stack and shout "Speeeeeedy!" First player to clear all cards wins the round.',
  },
  {
    id: 'prod-hodabt',
    sku: '3Z-HDB-02',
    nameAr: 'لعبة حُضبت - شرطة وحرامية',
    nameEn: 'Hodabt - Police & Thief Card Game',
    descriptionAr: 'لعبة الخداع والتحقيق المصرية الشهيرة من عالم زاجك! تقمص دور الشرطي (حُضبت)، الحرامي، أو النقاش ونط السور في مغامرة مثيرة تسعى فيها لكشف الهويات المخفية وتوزيع الشبهات.',
    descriptionEn: 'The iconic Egyptian bluffing & investigation game by 3alamzagak! Play as the Cop (Hodabt), Thief, Painter, or Parkour Master to uncover hidden identities and catch the culprit.',
    shortDescriptionAr: 'لعبة الذكاء والتمثيل والخداع الجماعية (3-8 لاعبين)',
    shortDescriptionEn: 'The social deduction & bluffing game for groups (3-8 Players)',
    price: 329,
    salePrice: 269,
    costPrice: 110,
    categoryId: 'cat-1',
    categoryNameAr: 'ألعاب الكروت',
    categoryNameEn: 'Card Games',
    brand: '3alamzagak',
    images: [
      '/cards/01_Hodabt_police_4K_bleed.png',
      '/cards/02_Al_Harami_thief_4K_bleed.png',
      '/cards/03_Al_Naqash_painter_4K_bleed.png',
      '/cards/04_Naz_El_Sour_parkour_4K_bleed.png',
      '/cards/05_Zod_Ma3gon_painter_4K_bleed.png',
      '/cards/06_Al_Hallaq_barber_4K_bleed.png',
    ],
    stock: 28,
    lowStockThreshold: 5,
    ageRecommendation: '8+',
    numberOfPlayers: '3-8 Players',
    minPlayers: 3,
    maxPlayers: 8,
    playingTimeMinutes: '20-30 mins',
    difficultyLevel: 'Easy',
    difficultyAr: 'سهل',
    language: 'Arabic',
    tags: ['Hodabt', 'Bluffing', 'Party', '3alamzagak Original'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    rating: 4.8,
    reviewCount: 29,
    howToPlayAr: 'يتم توزيع الأدوار السرية. يحاول الحرامي تنفيذ السرقة دون أن يكتشفه الشرطي "حُضبت". استخدم أدلة النقاش والحلاق لخداع الخصوم.',
    howToPlayEn: 'Secret roles are dealt. The thief attempts a heist without getting caught by Cop Hodabt. Use painter and barber hints to deceive opponents.',
  },
  {
    id: 'prod-koma-el10',
    sku: '3Z-KOM-03',
    nameAr: 'لعبة كومة الـ 10 الملكية',
    nameEn: 'Koma El 10 Royal Edition',
    descriptionAr: 'لعبة كروت استراتيجية فاخرة بطابع ملكي مصري. تجمع بين الحساب السريع، التجميع، وحركات التجميد الاستراتيجية لتشكيل الكومة الملكية والتفوق بالنقاط.',
    descriptionEn: 'Luxury royal Egyptian strategy card game. Combines fast math, set collection, and tactical freezing power cards to build the royal stack.',
    shortDescriptionAr: 'التحدي الملكي للكروت وحساب النقاط (2-6 لاعبين)',
    shortDescriptionEn: 'The royal stack & scoring card challenge (2-6 Players)',
    price: 399,
    salePrice: 319,
    costPrice: 150,
    categoryId: 'cat-1',
    categoryNameAr: 'ألعاب الكروت',
    categoryNameEn: 'Card Games',
    brand: '3alamzagak',
    images: [
      '/cards/Koma_El10_Crown_4K_9x5.5cm_Full.png',
      '/cards/Okef_3andak_9x5.5cm_Equal_Color_Bleed_4K.png',
    ],
    stock: 18,
    lowStockThreshold: 5,
    ageRecommendation: '10+',
    numberOfPlayers: '2-6 Players',
    minPlayers: 2,
    maxPlayers: 6,
    playingTimeMinutes: '25-40 mins',
    difficultyLevel: 'Medium',
    difficultyAr: 'متوسط',
    language: 'Bilingual',
    tags: ['Royal', 'Koma El 10', 'Strategy', '3alamzagak Original'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 14,
    howToPlayAr: 'اجمع مجموعات الكروت لتصل لقيمة 10 واستخدم كروت التاج الملكي لمضاعفة النقاط وحماية كومتك من السرقة.',
    howToPlayEn: 'Combine cards adding up to 10 and play Crown cards to double scores and shield your pile.',
  },
  {
    id: 'prod-okef-3andak',
    sku: '3Z-OKF-04',
    nameAr: 'لعبة أوقف عندك! (Okef 3andak)',
    nameEn: 'Okef 3andak! Action Card Game',
    descriptionAr: 'أوقف كروت منافسيك في لحظة الحسم! لعبة الأكشن والتحديات المباشرة من عالم زاجك. استخدم كروت الفيتو والمنع لتدمير خطط المنافس وفز بالجولة.',
    descriptionEn: 'Stop your rivals dead in their tracks! Fast action and direct challenge card game by 3alamzagak with vetoes and instant counters.',
    shortDescriptionAr: 'لعبة التحديات والحظر المباشر بين الأصدقاء',
    shortDescriptionEn: 'The action challenge & instant counter card game',
    price: 299,
    salePrice: 239,
    costPrice: 95,
    categoryId: 'cat-3',
    categoryNameAr: 'ألعاب الحفلات والتجمعات',
    categoryNameEn: 'Party Games',
    brand: '3alamzagak',
    images: [
      '/cards/Okef_3andak_9x5.5cm_Equal_Color_Bleed_4K.png',
      '/cards/Koma_El10_Crown_4K_9x5.5cm_Full.png',
    ],
    stock: 3,
    lowStockThreshold: 5,
    ageRecommendation: '8+',
    numberOfPlayers: '2-6 Players',
    minPlayers: 2,
    maxPlayers: 6,
    playingTimeMinutes: '15-25 mins',
    difficultyLevel: 'Easy',
    difficultyAr: 'سهل',
    language: 'Arabic',
    tags: ['Okef 3andak', 'Party', 'Action', 'Low Stock'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 22,
  },
  {
    id: 'prod-chess-luxury',
    sku: '3Z-CHS-05',
    nameAr: 'طقم شطرنج خشب الجوز الملكي 40 سم',
    nameEn: 'Luxury Royal Walnut Wooden Chess Set 40cm',
    descriptionAr: 'طقم شطرنج مصنوع يدوياً من أنقى أنواع خشب الجوز والزان الطبيعي، مع قطع شطرنج مبطنة بالجوخ الفاخر لملمس ناعم وحماية الطاولة. رقعة قابلة للطي تحتوي على مساحات تخزين مخملية للقطع.',
    descriptionEn: 'Handcrafted luxury chess board made of natural walnut and beech wood. Features velvet-bottom weighted pieces and a folding magnetic board with internal felt storage.',
    shortDescriptionAr: 'طاولة شطرنج خشبية فاخرة للمحترفين والهواة',
    shortDescriptionEn: 'Luxury wooden foldable chess set with weighted pieces',
    price: 1299,
    salePrice: 999,
    costPrice: 550,
    categoryId: 'cat-4',
    categoryNameAr: 'الشطرنج والألعاب الكلاسيكية',
    categoryNameEn: 'Chess & Classic Games',
    brand: '3alamzagak Crafts',
    images: [
      'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 12,
    lowStockThreshold: 3,
    ageRecommendation: '6+',
    numberOfPlayers: '2 Players',
    minPlayers: 2,
    maxPlayers: 2,
    playingTimeMinutes: '30-90 mins',
    difficultyLevel: 'Hard',
    difficultyAr: 'صعب',
    language: 'Bilingual',
    tags: ['Chess', 'Wooden', 'Luxury', 'Classic'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 5.0,
    reviewCount: 45,
  },
  {
    id: 'prod-tawla-egyptian',
    sku: '3Z-TWL-06',
    nameAr: 'طاولة زهر مصرية ملكية بالصدف الطبيعي 50 سم',
    nameEn: 'Handmade Mother of Pearl Egyptian Backgammon 50cm',
    descriptionAr: 'طاولة زهر شرقية كلاسيكية مطعمة بالصدف الطبيعي وخشب الأبنوس الرفيع. تشمل قشاط عاجي ونردين عالي الجودة لعشاق السهرات والدومينو وطاولة الـ 31 والفرنساوية.',
    descriptionEn: 'Classic handcrafted Egyptian Backgammon inlaid with genuine mother of pearl shell and ebony. Includes premium checkers and precision dice for traditional games.',
    shortDescriptionAr: 'طاولة زهر شرقية أصيلة مطعمة بالصدف',
    shortDescriptionEn: 'Authentic handcrafted inlaid Backgammon set',
    price: 1599,
    salePrice: 1349,
    costPrice: 700,
    categoryId: 'cat-4',
    categoryNameAr: 'الشطرنج والألعاب الكلاسيكية',
    categoryNameEn: 'Chess & Classic Games',
    brand: '3alamzagak Crafts',
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 7,
    lowStockThreshold: 2,
    ageRecommendation: '10+',
    numberOfPlayers: '2 Players',
    minPlayers: 2,
    maxPlayers: 2,
    playingTimeMinutes: '20-45 mins',
    difficultyLevel: 'Medium',
    difficultyAr: 'متوسط',
    language: 'Arabic',
    tags: ['Tawla', 'Backgammon', 'Mother of Pearl', 'Classic'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 19,
  },
  {
    id: 'prod-monopoly-cairo',
    sku: '3Z-MNP-07',
    nameAr: 'لعبة منوبولي الطبعة القاهرية (Monopoly Cairo Edition)',
    nameEn: 'Monopoly Cairo Edition Board Game',
    descriptionAr: 'اشترِ المعادي، الزمالك، التجمع الخامس، والأهرامات! النسخة القاهرية الخاصة مع النقود والأحياء المصرية والأحداث الكوميدية الخاصة بالطرق والمرور في القاهرة.',
    descriptionEn: 'Buy, sell, and trade Cairo’s iconic neighborhoods from Zamalek to the Pyramids! Features custom Egyptian currency, chance cards, and local landmarks.',
    shortDescriptionAr: 'لعبة العقارات والاستثمار بنكهة قاهرية أصيلة',
    shortDescriptionEn: 'The classic property trading game set in Cairo',
    price: 649,
    salePrice: 549,
    costPrice: 300,
    categoryId: 'cat-2',
    categoryNameAr: 'ألعاب الطاولة',
    categoryNameEn: 'Board Games',
    brand: 'Hasbro Gaming',
    images: [
      'https://images.unsplash.com/photo-1632501641765-e568d28b0015?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 25,
    lowStockThreshold: 5,
    ageRecommendation: '8+',
    numberOfPlayers: '2-6 Players',
    minPlayers: 2,
    maxPlayers: 6,
    playingTimeMinutes: '60-120 mins',
    difficultyLevel: 'Medium',
    difficultyAr: 'متوسط',
    language: 'Bilingual',
    tags: ['Monopoly', 'Cairo', 'Family', 'Board Games'],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: 'prod-catan-official',
    sku: '3Z-CTN-08',
    nameAr: 'لعبة مستوطنو كاتان (Catan Official Board Game)',
    nameEn: 'Catan Official 5th Edition Board Game',
    descriptionAr: 'لعبة التداول والاستراتيجية العالمية الأولى! ابنِ المستوطنات، تداول الموارد كالطوب والخشب والقمح مع اللاعبين، وسيطر على جزيرة كاتان.',
    descriptionEn: 'The world-renowned strategy board game! Trade resources, build roads and settlements, and colonize the island of Catan.',
    shortDescriptionAr: 'أشهر لعبة تداول وتأسيس مستعمرات استراتيجية في العالم',
    shortDescriptionEn: 'The classic resource management & trading board game',
    price: 1199,
    salePrice: 989,
    costPrice: 600,
    categoryId: 'cat-5',
    categoryNameAr: 'ألعاب الذكاء والاستراتيجية',
    categoryNameEn: 'Strategy Games',
    brand: 'Catan Studio',
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 14,
    lowStockThreshold: 4,
    ageRecommendation: '10+',
    numberOfPlayers: '3-4 Players',
    minPlayers: 3,
    maxPlayers: 4,
    playingTimeMinutes: '60-90 mins',
    difficultyLevel: 'Hard',
    difficultyAr: 'صعب',
    language: 'English',
    tags: ['Catan', 'Strategy', 'Resource Management', 'Top Rated'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: 'prod-sleeves-gold',
    sku: '3Z-ACC-09',
    nameAr: 'جرابات حماية الكروت شفافة فاخرة 100 جراب (Matte Gold)',
    nameEn: 'Luxury Matte Clear Premium Card Sleeves (Pack of 100)',
    descriptionAr: 'احمِ أوراق لعبتك المفضلة من الماء، السوائل، والتلف أثناء اللعب الشديد. ملمس مطفي لمنع الانزلاق وشفافية كريستالية عالية.',
    descriptionEn: 'Protect your favorite gaming cards from spills and wear. Non-glare matte texture with crystal-clear viewing.',
    shortDescriptionAr: 'حماية فائقة لكروت الألعاب 100 جراب',
    shortDescriptionEn: '100 premium matte card protector sleeves',
    price: 129,
    salePrice: 99,
    costPrice: 35,
    categoryId: 'cat-6',
    categoryNameAr: 'إكسسوارات الألعاب',
    categoryNameEn: 'Accessories & Sleeves',
    brand: '3alamzagak Protection',
    images: [
      'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 120,
    lowStockThreshold: 20,
    ageRecommendation: 'Any',
    numberOfPlayers: '1+',
    minPlayers: 1,
    maxPlayers: 10,
    playingTimeMinutes: 'N/A',
    difficultyLevel: 'Easy',
    difficultyAr: 'سهل',
    language: 'Bilingual',
    tags: ['Sleeves', 'Accessories', 'Protection'],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: 'prod-dice-set-metal',
    sku: '3Z-DCE-10',
    nameAr: 'طقم نرد معدني مذهب فاخر RPG (7 قطع مع بيت مخملي)',
    nameEn: 'Luxury Gold Metal RPG Dice Set (7 Polyhedral Dice + Velvet Pouch)',
    descriptionAr: 'طقم نرد معدني بحواف حادة ولمعة ذهبية ملكية مخصصة لألعاب الدراجونز، الشطرنج، والدومينو. يأتي في حقيبة مخملية سوداء بشعار عالم زاجك.',
    descriptionEn: 'Solid metal gold-finished polyhedral dice set with razor-sharp edges and satisfying heavy weight. Includes custom 3alamzagak velvet pouch.',
    shortDescriptionAr: 'نرد معدني ثقيل فاخر للمجموعات والألعاب',
    shortDescriptionEn: 'Heavyweight metal gold RPG polyhedral dice set',
    price: 299,
    salePrice: 249,
    costPrice: 90,
    categoryId: 'cat-6',
    categoryNameAr: 'إكسسوارات الألعاب',
    categoryNameEn: 'Accessories & Sleeves',
    brand: '3alamzagak Gold',
    images: [
      'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 35,
    lowStockThreshold: 8,
    ageRecommendation: '12+',
    numberOfPlayers: '1+',
    minPlayers: 1,
    maxPlayers: 8,
    playingTimeMinutes: 'N/A',
    difficultyLevel: 'Easy',
    difficultyAr: 'سهل',
    language: 'Bilingual',
    tags: ['Dice', 'Metal', 'Gold', 'RPG'],
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    rating: 5.0,
    reviewCount: 26,
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minOrderValue: 200,
    maxDiscount: 100,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    usageLimit: 1000,
    timesUsed: 142,
    perCustomerLimit: 1,
    isActive: true,
  },
  {
    id: 'coup-2',
    code: 'FREESHIP',
    type: 'free_shipping',
    value: 0,
    minOrderValue: 400,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    usageLimit: 500,
    timesUsed: 89,
    perCustomerLimit: 2,
    isActive: true,
  },
  {
    id: 'coup-3',
    code: 'ZAGAK50',
    type: 'fixed',
    value: 50,
    minOrderValue: 500,
    startDate: '2026-08-01',
    endDate: '2026-10-31',
    usageLimit: 200,
    timesUsed: 37,
    perCustomerLimit: 1,
    isActive: true,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-speeeeeedy',
    customerName: 'أحمد محمود',
    rating: 5,
    title: 'لعبة أسطورية وبديهة خطيرة!',
    comment: 'اللعبة سريعة وممتعة جداً للسهرات مع العيلة والأصحاب. الجودة والكروت خامة فاخرة جداً تسلم إيديكم عالم زاجك!',
    date: '2026-09-02',
    isVerifiedPurchase: true,
    status: 'Approved',
    adminReply: 'شكراً لك أستاذ أحمد! نتمنى لك دائماً أوقات مليئة بالحماس مع عالم زاجك 💛',
  },
  {
    id: 'rev-2',
    productId: 'prod-hodabt',
    customerName: 'سارة شريف',
    rating: 5,
    title: 'ضحك غير طبيعي في لعبة حُضبت',
    comment: 'لعبناها في قعدة الخميس والكل كان بيموت من الضحك! التصاميم والرسم على الكروت دمها خفيف جداً.',
    date: '2026-08-28',
    isVerifiedPurchase: true,
    status: 'Approved',
  },
  {
    id: 'rev-3',
    productId: 'prod-chess-luxury',
    customerName: 'Tarek Al-Masry',
    rating: 5,
    title: 'Masterpiece Wooden Chess',
    comment: 'Exceptional craftsmanship! The walnut finish and weighted felt pieces feel super premium on the fingers.',
    date: '2026-08-20',
    isVerifiedPurchase: true,
    status: 'Approved',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: '3Z-98421',
    customerId: 'cust-1',
    customerName: 'عمر خالد',
    customerEmail: 'omar.khaled@gmail.com',
    customerPhone: '01012345678',
    items: [
      {
        productId: 'prod-speeeeeedy',
        productNameAr: 'لعبة سبيدي (Speeeeeedy!) الاصدار الذهبي',
        productNameEn: 'Speeeeeedy! Card Game Gold Edition',
        image: '/cards/Speeeeeedy_Minimalist_Full_Card_4K_9x5.5cm.png',
        price: 289,
        quantity: 2,
      },
      {
        productId: 'prod-sleeves-gold',
        productNameAr: 'جرابات حماية الكروت شفافة فاخرة 100 جراب',
        productNameEn: 'Luxury Matte Clear Premium Card Sleeves',
        image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=800&q=80',
        price: 99,
        quantity: 1,
      }
    ],
    subtotal: 677,
    discount: 50,
    shippingFee: 0,
    total: 627,
    couponCode: 'ZAGAK50',
    status: 'Delivered',
    paymentMethod: 'cod',
    paymentStatus: 'Paid',
    shippingAddress: {
      id: 'addr-1',
      title: 'المنزل',
      fullName: 'عمر خالد',
      phone: '01012345678',
      governorate: 'القاهرة',
      city: 'المعادي',
      streetAddress: 'شارع 9 - صيدلية المعادي',
      building: 'مبنى 14 - شقة 4',
      isDefault: true,
    },
    deliveryMethod: 'توصيل قياسي (24 - 48 ساعة)',
    trackingNumber: 'EG-3Z-98421-TRK',
    timeline: [
      { status: 'Pending', date: '2026-09-01 14:20' },
      { status: 'Confirmed', date: '2026-09-01 15:00' },
      { status: 'Processing', date: '2026-09-01 16:30' },
      { status: 'Packed', date: '2026-09-01 18:10' },
      { status: 'Shipped', date: '2026-09-02 09:00' },
      { status: 'Out for Delivery', date: '2026-09-02 11:30' },
      { status: 'Delivered', date: '2026-09-02 14:45', notes: 'تم التسليم بواسطة المندوب واستلام المبلغ' },
    ],
    createdAt: '2026-09-01T14:20:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: '3Z-98422',
    customerId: 'cust-2',
    customerName: 'مريم علي',
    customerEmail: 'mariam.ali@yahoo.com',
    customerPhone: '01198765432',
    items: [
      {
        productId: 'prod-hodabt',
        productNameAr: 'لعبة حُضبت - شرطة وحرامية',
        productNameEn: 'Hodabt - Police & Thief Card Game',
        image: '/cards/01_Hodabt_police_4K_bleed.png',
        price: 269,
        quantity: 1,
      },
      {
        productId: 'prod-koma-el10',
        productNameAr: 'لعبة كومة الـ 10 الملكية',
        productNameEn: 'Koma El 10 Royal Edition',
        image: '/cards/Koma_El10_Crown_4K_9x5.5cm_Full.png',
        price: 319,
        quantity: 1,
      }
    ],
    subtotal: 588,
    discount: 58.8,
    shippingFee: 45,
    total: 574.2,
    couponCode: 'WELCOME10',
    status: 'Shipped',
    paymentMethod: 'card',
    paymentStatus: 'Paid',
    shippingAddress: {
      id: 'addr-2',
      title: 'العمل',
      fullName: 'مريم علي',
      phone: '01198765432',
      governorate: 'الجيزة',
      city: 'الشيخ زايد',
      streetAddress: 'الكمبوند السكني - التوسعات الشمالية',
      building: 'فيلا 8B',
      isDefault: true,
    },
    deliveryMethod: 'توصيل قياسي',
    trackingNumber: 'EG-3Z-98422-TRK',
    timeline: [
      { status: 'Pending', date: '2026-09-07 10:15' },
      { status: 'Confirmed', date: '2026-09-07 10:45' },
      { status: 'Processing', date: '2026-09-07 12:00' },
      { status: 'Packed', date: '2026-09-07 16:00' },
      { status: 'Shipped', date: '2026-09-08 08:30' },
    ],
    createdAt: '2026-09-07T10:15:00Z',
  }
];

export const INITIAL_INVENTORY_LOGS: InventoryTransaction[] = [
  {
    id: 'inv-1',
    productId: 'prod-speeeeeedy',
    productName: 'لعبة سبيدي (Speeeeeedy!) الاصدار الذهبي',
    previousStock: 50,
    newStock: 48,
    change: -2,
    reason: 'Order Deduction',
    adminUser: 'System (Order 3Z-98421)',
    date: '2026-09-01 14:20',
  },
  {
    id: 'inv-2',
    productId: 'prod-sleeves-gold',
    productName: 'جرابات حماية الكروت شفافة فاخرة 100 جراب',
    previousStock: 70,
    newStock: 120,
    change: +50,
    reason: 'Restock',
    adminUser: 'Super Admin',
    date: '2026-08-25 11:00',
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'مدير عالم زاجك',
    email: 'admin@3alamzagak.com',
    phone: '01000003Z3Z',
    role: 'Super Admin',
    createdAt: '2026-01-01',
    totalSpent: 0,
    ordersCount: 0,
    addresses: [],
  },
  {
    id: 'cust-1',
    name: 'عمر خالد',
    email: 'omar.khaled@gmail.com',
    phone: '01012345678',
    role: 'Customer',
    createdAt: '2026-02-15',
    totalSpent: 2840,
    ordersCount: 4,
    addresses: [
      {
        id: 'addr-1',
        title: 'المنزل',
        fullName: 'عمر خالد',
        phone: '01012345678',
        governorate: 'القاهرة',
        city: 'المعادي',
        streetAddress: 'شارع 9 - صيدلية المعادي',
        building: 'مبنى 14 - شقة 4',
        isDefault: true,
      }
    ],
  }
];

export const INITIAL_BANNERS: HomepageBanner[] = [
  {
    id: 'ban-1',
    titleAr: 'تحدى أصحابك في عالم زاجك!',
    titleEn: 'Challenge Your Squad at 3alamzagak!',
    subtitleAr: 'أفخم ألعاب الكروت والطاولة بتصاميم ومشاعر لا تُنسى.',
    subtitleEn: 'The finest card & board games designed for unforgettable memories.',
    ctaTextAr: 'تسوق التشكيلة الجديدة',
    ctaTextEn: 'Shop New Arrivals',
    link: '/shop',
    imageUrl: '/cards/Speeeeeedy_Minimalist_Full_Card_4K_9x5.5cm.png',
    badgeAr: 'الأصلي والخصومات الحصرية',
    badgeEn: 'Original & Exclusive Deals',
    isActive: true,
  }
];

export const DEFAULT_SETTINGS: StoreSettings = {
  storeNameAr: 'عالم زاجك - 3alamzagak',
  storeNameEn: '3alamzagak Board & Card Games',
  supportPhone: '+20 100 333 4488',
  supportEmail: 'support@3alamzagak.com',
  currency: 'EGP',
  freeShippingThreshold: 600,
  defaultShippingFee: 45,
  taxRate: 0,
  facebookUrl: 'https://facebook.com/3alamzagak',
  instagramUrl: 'https://instagram.com/3alamzagak',
  tiktokUrl: 'https://tiktok.com/@3alamzagak',
};
